//! §14.8.4's forty-one standard structure types, onto AccessKit's roles.
//!
//! # Two vocabularies, and what one says that the other cannot
//!
//! ISO 32000-2 §14.8.4 names forty-one structure types across five tables; `accesskit::Role` has
//! about two hundred, drawn from ARIA, from the `DPub` module and from three desktop platforms'
//! own trees. Most of the forty-one land on one exactly. The rest are recorded here rather than
//! defaulted to [`accesskit::Role::Unknown`], because a mapping that quietly loses a distinction
//! is worse than one that says which distinction it lost:
//!
//! | §14.8.4 | becomes | and what is lost |
//! |---|---|---|
//! | `DocumentFragment` | `Document` | AccessKit has no fragment role. §14.8.4.3's difference is that "the structure of the fragment may be incomplete", which is not something an assistive technology can act on |
//! | `Part` | `Group` | `Role::DocPart` exists and is the `DPub` `doc-part`, "a major thematic section" — which asserts the hierarchy §14.8.4.4 says a `Part` is explicitly *without*: "a grouping of structure elements without consideration for their hierarchy" |
//! | `Title` | `Heading` | no title role; a title is what a person navigating by heading wants to land on. The *level* is not set, because §14.8.4.5 gives a `Title` none |
//! | `FENote` | `DocFootnote` | one PDF type for two `DPub` roles. §14.8.4.5 calls it "footnotes and endnotes" and AccessKit splits them; the footnote is the commoner and the endnote loses its name |
//! | `Sub` | `Group` | no sub-block role anywhere in AccessKit |
//! | `Lbl` | `Label` | inside a list this is the bullet, and `Role::ListMarker` would say so — but §14.8.4.7.2 makes `Lbl` general ("content that distinguishes it from other content inside the same parent element"), and a line number in a `Sub` is not a marker |
//! | `Annot` | `Group` | AccessKit has no role for "content associated with an annotation", and which annotation it is is §14.7.5.3's `/OBJR`, which this program locates but does not classify |
//! | `Form` | `Group` | §14.8.4.7.2 makes this **one widget annotation**, not a form — so `Role::Form` would be wrong twice over. What it *should* become is the field's own control role, which needs the widget behind the `/OBJR` and §12.7's field type. Named in `doc/todo/31` |
//! | `RB`, `RP`, `WT`, `WP` | `Label` | AccessKit has `Ruby` and `RubyAnnotation` and nothing for the base text, the punctuation or warichu's halves |
//! | `Warichu` | `Group` | no warichu role |
//! | `LBody` | `GenericContainer` | no list-item-body role; a list item's content belongs to the item, which is what the platform filter does with this one |
//! | `TH` | `ColumnHeader` | AccessKit splits header cells by axis and §14.8.4.8.3 leaves the axis to the `Scope` attribute, which this program does not read here. Named in `doc/todo/31` |
//! | `Figure` | `Image` | `Role::Figure` exists and becomes an AT-SPI `Panel`, which says nothing; a `Figure` is graphical content that §14.8.4.8.5 says "should have either an `Alt` entry or an `ActualText` entry", which is an image with alternative text |
//! | anything else | `Group`, described | §14.8.4.1 requires a tagged document's types to be standard or role mapped to standard ones, so a name arriving here is a defect in the *document*. The name is put in the node's description rather than dropped |
//!
//! # Two roles the platform filters out, and the rule that follows
//!
//! `accesskit_consumer`'s `common_filter` — which the AT-SPI adapter uses — removes a
//! [`accesskit::Role::GenericContainer`] or [`accesskit::Role::TextRun`] node from the tree an
//! assistive technology sees and lifts its children into its parent. That is exactly right for
//! `NonStruct`, whose clause says the same thing in its own words: "[a] grouping element having
//! no inherent structural significance … it should not be interpreted or exported to other
//! document formats. Its descendants shall be processed".
//!
//! It is also a way to lose text, because a node's *label* goes with the node. So the mapping
//! takes a second input — whether this element has anything to say — and a type that would
//! otherwise be filtered out becomes a [`accesskit::Role::Label`] when it does.
//!
//! **`Artifact` is the one exception, and it is deliberate.** §14.8.2.2.1 divides a page into the
//! author's real content and "[a]ll other content … whether generated by the PDF writer in the
//! course of pagination, layout, or other mechanical processes or introduced by the document
//! author for decoration". A running head read aloud on every page is what tagging exists to
//! prevent, so an artifact's text is dropped rather than promoted.

use accesskit::Role;
use pdf_model::structure::StandardType;

/// What one structure type becomes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mapping {
    /// The platform role.
    pub role: Role,
    /// §14.8.4.5's `Hn` level, where the type states one.
    ///
    /// > With n being a sequence of digits representing an unsigned integer greater than or equal
    /// > to 1
    ///
    /// so the level is part of the *name* and `H7` is as legal as `H1`. `None` for `H`, whose
    /// level "is not indicated through this structure element, but instead is derived from the
    /// nesting of the logical structure" — a derivation this program does not do, and a level
    /// invented here would be a claim about the document rather than a reading of it.
    pub level: Option<u32>,
    /// The type the document wrote, where §14.8.4 does not define it.
    ///
    /// `Some` is a finding about the *document*: §14.8.4.1 requires "[a]ll structure elements
    /// occurring within a tagged PDF document" to have "a type matching one of those defined as a
    /// Standard Structure Type, or a role map providing a mapping from the non-standard type to a
    /// Standard Structure Type", and the role map has already been applied by the time a name
    /// reaches here. It is carried into the node's description rather than dropped, because a
    /// person whose reader says "group" wants to know that the file, not the reader, is why.
    pub unmapped: Option<String>,
    /// Whether a label may be put on the node.
    ///
    /// `false` for `Artifact` alone: §14.8.2.2 makes an artifact content that is on the page and
    /// is not the document's, and speaking it is what tagging exists to avoid.
    pub speaks: bool,
}

/// Maps one element's structure type onto the platform's vocabulary.
///
/// `speaking` is whether the element has anything of its own to say, which decides one thing: a
/// type that would otherwise become a role the platform filters out of the tree keeps its text by
/// becoming a [`Role::Label`] instead. See this module's own documentation.
#[must_use]
pub fn map(role: &str, speaking: bool) -> Mapping {
    let Some(standard) = StandardType::read(role) else {
        return Mapping {
            role: Role::Group,
            level: None,
            unmapped: Some(role.to_owned()),
            speaks: true,
        };
    };
    #[expect(
        clippy::match_same_arms,
        reason = "the arms are §14.8.4's own five tables in the standard's order, and merging \
                  the ones that happen to land on the same role would hide which table a type \
                  came from — which is the thing this mapping has to be readable against"
    )]
    let (mapped, level) = match &standard {
        // Table 364, document level.
        StandardType::Document | StandardType::DocumentFragment => (Role::Document, None),
        // Table 365, grouping level.
        StandardType::Part => (Role::Group, None),
        StandardType::Section | StandardType::Division => (Role::Section, None),
        // "content that is distinct from other content within its parent structure element",
        // whose examples are callouts, sidebars and commentary — which is ARIA's `complementary`.
        StandardType::Aside => (Role::Complementary, None),
        StandardType::NonStructural => (Role::GenericContainer, None),
        // Table 366, block level.
        StandardType::Paragraph => (Role::Paragraph, None),
        StandardType::Heading(level) => (Role::Heading, Some(*level)),
        StandardType::UnnumberedHeading | StandardType::Title => (Role::Heading, None),
        StandardType::FootnoteOrEndnote => (Role::DocFootnote, None),
        // Table 367, sub-block level.
        StandardType::SubBlock => (Role::Group, None),
        // Table 368, inline level.
        StandardType::Label => (Role::Label, None),
        StandardType::Span => (Role::Label, None),
        StandardType::Emphasis => (Role::Emphasis, None),
        StandardType::Strong => (Role::Strong, None),
        StandardType::Link => (Role::Link, None),
        StandardType::Annotation | StandardType::Form => (Role::Group, None),
        // Table 369, ruby and warichu.
        StandardType::Ruby => (Role::Ruby, None),
        StandardType::RubyText => (Role::RubyAnnotation, None),
        StandardType::RubyBase
        | StandardType::RubyPunctuation
        | StandardType::WarichuText
        | StandardType::WarichuPunctuation => (Role::Label, None),
        StandardType::Warichu => (Role::Group, None),
        // Table 370, lists.
        StandardType::List => (Role::List, None),
        StandardType::ListItem => (Role::ListItem, None),
        StandardType::ListItemBody => (Role::GenericContainer, None),
        // Table 371, tables.
        StandardType::Table => (Role::Table, None),
        StandardType::TableRow => (Role::Row, None),
        StandardType::TableHeader => (Role::ColumnHeader, None),
        StandardType::TableData => (Role::Cell, None),
        StandardType::TableHead | StandardType::TableBody | StandardType::TableFoot => {
            (Role::RowGroup, None)
        }
        // Tables 372 to 375.
        StandardType::Caption => (Role::Caption, None),
        StandardType::Figure => (Role::Image, None),
        StandardType::Formula => (Role::Math, None),
        StandardType::Artifact => (Role::GenericContainer, None),
    };
    let speaks = standard != StandardType::Artifact;
    Mapping {
        // A node the platform would filter out takes its label with it, so a type that has
        // something to say may not have one. `Artifact` is not promoted, because its text is
        // what §14.8.2.2 says is not the document's content.
        role: if speaking && speaks && filtered_out(mapped) {
            Role::Label
        } else {
            mapped
        },
        level,
        unmapped: None,
        speaks,
    }
}

/// Whether the platform adapter drops a node of this role and lifts its children.
///
/// `accesskit_consumer::common_filter`, which every AccessKit platform adapter applies, answers
/// `ExcludeNode` for exactly these two. Stated here as a fact about the library this crate
/// depends on, and asserted against it by `a_filtered_role_never_carries_text`.
fn filtered_out(role: Role) -> bool {
    matches!(role, Role::GenericContainer | Role::TextRun)
}

#[cfg(test)]
mod tests {
    use super::{Mapping, map};
    use accesskit::Role;
    use pdf_model::structure::StandardType;

    /// Every one of §14.8.4's forty-one types maps, and none of them lands on `Unknown`.
    ///
    /// The list is the standard's five tables, written out: 2 document level (Table 364), 5
    /// grouping (365), 5 block (366) — `Hn` counted once — 1 sub-block (367), 7 general inline
    /// (368), 7 ruby and warichu (369), 3 list (370), 7 table (371), and one each for Tables 372
    /// to 375. Forty-one, which is what §14.8.4 defines.
    #[test]
    fn every_standard_structure_type_maps_to_something_that_is_not_unknown() {
        const TYPES: [&str; 41] = [
            "Document",
            "DocumentFragment",
            "Part",
            "Sect",
            "Div",
            "Aside",
            "NonStruct",
            "P",
            "H1",
            "H",
            "Title",
            "FENote",
            "Sub",
            "Lbl",
            "Span",
            "Em",
            "Strong",
            "Link",
            "Annot",
            "Form",
            "Ruby",
            "RB",
            "RT",
            "RP",
            "Warichu",
            "WT",
            "WP",
            "L",
            "LI",
            "LBody",
            "Table",
            "TR",
            "TH",
            "TD",
            "THead",
            "TBody",
            "TFoot",
            "Caption",
            "Figure",
            "Formula",
            "Artifact",
        ];
        for name in TYPES {
            assert!(
                StandardType::read(name).is_some(),
                "{name} is one of §14.8.4's own names"
            );
            let mapping = map(name, false);
            assert_eq!(mapping.unmapped, None, "{name} is standard");
            assert_ne!(
                mapping.role,
                Role::Unknown,
                "{name} landed on Unknown, which is the default this mapping exists to avoid"
            );
        }
    }

    /// §14.8.4.5's `Hn` carries its level, and `H` deliberately does not.
    #[test]
    fn a_numbered_heading_carries_its_level_and_an_unnumbered_one_does_not() {
        assert_eq!(map("H1", true).level, Some(1));
        assert_eq!(map("H6", true).level, Some(6));
        // "with n being a sequence of digits representing an unsigned integer greater than or
        // equal to 1" — so a level nobody enumerated is still a level.
        assert_eq!(map("H17", true).level, Some(17));
        assert_eq!(map("H", true).role, Role::Heading);
        assert_eq!(map("H", true).level, None);
    }

    /// A role the platform filters out never carries the element's text away with it.
    #[test]
    fn a_filtered_role_never_carries_text() {
        // `NonStruct` is the type whose clause asks to be ignored, and the mapping obeys that
        // where there is nothing to lose.
        assert_eq!(map("NonStruct", false).role, Role::GenericContainer);
        assert_eq!(map("LBody", false).role, Role::GenericContainer);
        // And keeps the node where there is.
        assert_eq!(map("NonStruct", true).role, Role::Label);
        assert_eq!(map("LBody", true).role, Role::Label);
    }

    /// §14.8.2.2's artifact keeps its filtered role and is never spoken.
    #[test]
    fn an_artifact_is_not_spoken_even_when_it_has_text() {
        let Mapping { role, speaks, .. } = map("Artifact", true);
        assert_eq!(role, Role::GenericContainer);
        assert!(
            !speaks,
            "§14.8.2.2 makes an artifact content that is not the document's"
        );
    }

    /// A type §14.8.4 does not define is named rather than defaulted.
    ///
    /// The role map has already been applied by the time a name reaches this function, so a name
    /// arriving here is §14.8.4.1's requirement unmet by the document.
    #[test]
    fn a_type_outside_the_standard_set_is_carried_rather_than_dropped() {
        let mapping = map("Advertising", true);
        assert_eq!(mapping.role, Role::Group);
        assert_eq!(mapping.unmapped.as_deref(), Some("Advertising"));
    }
}
