//! Shadings, checked by the colour they actually put on the page.
//!
//! A shading is one of the few things whose correctness can be stated exactly: at a known
//! point it must be a known colour. That makes these tests worth more than an eye can
//! give — a gradient running the wrong way, or extending where it should stop, looks
//! entirely plausible in a rendered page and is obvious against a numeric expectation.

#![expect(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "test code: a malformed fixture or an out-of-range pixel should fail loudly, \
              and the fixtures are small enough that no index can overflow"
)]

use std::fmt::Write as _;

use pdf_render::{Rasterizer, TargetSpec};
use pdf_syntax::Document;
use render_cpu::CpuRasterizer;
use test_scenes::{TYPE4_PAGE, TYPE4_SPLIT, Type4Comments, type4_comment_pair};

/// Pixel budget, far above the small pages these tests build.
const GENEROUS: u64 = 1 << 30;

/// Assembles a one-page PDF around a content stream and some extra objects.
///
/// Written out by hand rather than through a builder so the fixture is readable as PDF:
/// what is being tested is our reading of the format, and a fixture generated by our own
/// code would share any misunderstanding.
fn pdf_with(shading: &str, content: &str) -> Vec<u8> {
    pdf_with_extra(shading, content, "")
}

/// As [`pdf_with`], with `extra` appended as further indirect objects numbered from 7.
fn pdf_with_extra(shading: &str, content: &str, extra: &str) -> Vec<u8> {
    let body = format!(
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
         2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n\
         3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] \
         /Resources << /Shading << /Sh0 5 0 R >> /Pattern << /P0 6 0 R >> >> \
         /Contents 4 0 R >>\nendobj\n\
         4 0 obj\n<< /Length {} >>\nstream\n{content}\nendstream\nendobj\n\
         5 0 obj\n{shading}\nendobj\n\
         6 0 obj\n<< /PatternType 2 /Shading 5 0 R >>\nendobj\n{extra}",
        content.len().saturating_add(1)
    );

    assemble(&body)
}

/// Wraps a body of numbered objects in a header, a cross-reference table and a trailer.
fn assemble(body: &str) -> Vec<u8> {
    let mut out = String::from("%PDF-1.7\n");
    let mut offsets = Vec::new();
    for object in body.split_inclusive("endobj\n") {
        offsets.push(out.len());
        out.push_str(object);
    }
    let xref_at = out.len();
    let size = offsets.len().saturating_add(1);
    let _ = writeln!(out, "xref\n0 {size}");
    out.push_str("0000000000 65535 f \n");
    for offset in &offsets {
        let _ = writeln!(out, "{offset:010} 00000 n ");
    }
    let _ = write!(
        out,
        "trailer\n<< /Size {size} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    );
    out.into_bytes()
}

/// Renders a fixture at one pixel per unit and returns the pixels.
fn render(bytes: Vec<u8>) -> pdf_render::Raster {
    render_at(bytes, 1.0)
}

/// Renders a fixture at `scale` pixels per unit and returns the pixels.
fn render_at(bytes: Vec<u8>, scale: f32) -> pdf_render::Raster {
    let document = Document::open(bytes).expect("the fixture is a valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let interpretation = pdf_model::interpret(&document, &page);
    assert!(
        interpretation.is_complete(),
        "the fixture should draw completely: {:?}",
        interpretation.unsupported
    );
    let list = interpretation.display_list;
    let target = TargetSpec::for_page(&list, scale, GENEROUS).expect("valid target");
    // A transparent background, so that alpha says exactly whether anything was painted.
    // The default white one would make every pixel opaque and every such assertion
    // vacuous — which is how the first draft of these tests managed to pass while
    // checking nothing.
    CpuRasterizer::new()
        .with_medium(pdf_render::Medium::NONE)
        .rasterize(&list, target)
        .expect("supported")
}

/// The colour at a pixel, as `(r, g, b, a)`.
fn pixel(raster: &pdf_render::Raster, x: u32, y: u32) -> (u8, u8, u8, u8) {
    let at = ((y.saturating_mul(raster.width)).saturating_add(x) as usize).saturating_mul(4);
    (
        raster.data[at],
        raster.data[at + 1],
        raster.data[at + 2],
        raster.data[at + 3],
    )
}

/// A red-to-blue axial shading running left to right across the page.
const RED_TO_BLUE: &str = "<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [0 0 100 0] \
                           /Extend [true true] \
                           /Function << /FunctionType 2 /Domain [0 1] \
                           /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";

/// One shading object painted twice is built once (ADR 0069).
///
/// A shading's colours are the whole cost of building it — every `/Function` parsed and a
/// [`pdf_render::Ramp`] of 256 evaluations of them — and none of that depends on where it is
/// painted. `bug1721218_reduced.pdf` runs `sh` 3576 times over three function objects, and
/// building for each one was a fifth of that page.
///
/// The assertion is pointer identity, which is the only thing that distinguishes a cache
/// from a fast rebuild, and it is checked through the display list rather than through the
/// cache's own API: what matters is that the two commands *share* their colours.
///
/// The colour space here is an array rather than the name `/DeviceRGB` on purpose — a name
/// is resolved through the resource dictionary in force (§8.6.5.1, and §8.6.5.6 for the
/// device names), so `shading::Cache` refuses to key one by the object alone. The next test
/// is that refusal.
#[test]
fn one_shading_object_painted_twice_is_built_once() {
    let shading = "<< /ShadingType 2 /ColorSpace [/CalRGB << /WhitePoint [0.9505 1 1.089] >>] \
                   /Coords [0 0 100 0] /Extend [true true] \
                   /Function << /FunctionType 2 /Domain [0 1] /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";
    let document =
        Document::open(pdf_with(shading, "q /Sh0 sh Q q 1 0 0 1 0 20 cm /Sh0 sh Q")).expect("PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let list = pdf_model::interpret(&document, &page).display_list;

    let kinds: Vec<_> = list
        .commands()
        .iter()
        .filter_map(|command| match command {
            pdf_render::Command::Fill {
                paint: pdf_render::Paint::Shading(shading),
                ..
            } => Some(std::sync::Arc::clone(&shading.kind)),
            _ => None,
        })
        .collect();
    assert_eq!(kinds.len(), 2, "two `sh` operators, two commands");
    assert!(
        std::sync::Arc::ptr_eq(&kinds[0], &kinds[1]),
        "and one set of colours between them"
    );
}

/// A shading whose colour space is a *name* is not shared between resource dictionaries.
///
/// §8.6.5.1 resolves a colour space name through the `/ColorSpace` subdictionary of the
/// resources in force, so one shading object under two resource dictionaries can be two
/// different sets of colours. This fixture is that file: `/Sh0` names `/Space`, the page
/// defines it as a `Separation` inked red and the form defines the same name as one inked
/// blue, and the two paintings must not agree.
///
/// A cache keyed by the object alone would answer the first colour twice. This is the case
/// that decides the key, and it is worth a fixture rather than a comment because nothing
/// else in the tree would notice.
#[test]
fn a_named_colour_space_is_resolved_against_the_resources_that_paint_it() {
    let separation = |tint: &str| {
        format!(
            "[/Separation /Ink /DeviceRGB << /FunctionType 2 /Domain [0 1] \
             /C0 [1 1 1] /C1 {tint} /N 1 >>]"
        )
    };
    let page = "q /Sh0 sh Q q 1 0 0 1 0 50 cm /Fm Do Q";
    let form = "/Sh0 sh";
    let body = format!(
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
         2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n\
         3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] \
         /Resources << /Shading << /Sh0 5 0 R >> /XObject << /Fm 6 0 R >> \
         /ColorSpace << /Space {} >> >> /Contents 4 0 R >>\nendobj\n\
         4 0 obj\n<< /Length {} >>\nstream\n{page}\nendstream\nendobj\n\
         5 0 obj\n<< /ShadingType 2 /ColorSpace /Space /Coords [0 0 100 0] \
         /Extend [true true] /Function << /FunctionType 2 /Domain [0 1] \
         /C0 [1] /C1 [1] /N 1 >> >>\nendobj\n\
         6 0 obj\n<< /Type /XObject /Subtype /Form /BBox [0 0 100 50] \
         /Resources << /Shading << /Sh0 5 0 R >> /ColorSpace << /Space {} >> >> \
         /Length {} >>\nstream\n{form}\nendstream\nendobj\n",
        separation("[1 0 0]"),
        page.len().saturating_add(1),
        separation("[0 0 1]"),
        form.len().saturating_add(1),
    );
    let mut out = String::from("%PDF-1.7\n");
    let mut offsets = Vec::new();
    for object in body.split_inclusive("endobj\n") {
        offsets.push(out.len());
        out.push_str(object);
    }
    let xref_at = out.len();
    let size = offsets.len().saturating_add(1);
    let _ = writeln!(out, "xref\n0 {size}");
    out.push_str("0000000000 65535 f \n");
    for offset in &offsets {
        let _ = writeln!(out, "{offset:010} 00000 n ");
    }
    let _ = write!(
        out,
        "trailer\n<< /Size {size} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    );

    let raster = render(out.into_bytes());
    // Device row 75 is the page's own `sh`, row 25 the form's; both are painted at full tint.
    assert_eq!(pixel(&raster, 50, 75).0, 255, "the page's ink is red");
    assert_eq!(pixel(&raster, 50, 75).2, 0);
    assert_eq!(pixel(&raster, 50, 25).2, 255, "the form's is blue");
    assert_eq!(pixel(&raster, 50, 25).0, 0);
}

#[test]
fn an_axial_shading_runs_from_its_first_colour_to_its_second() {
    // `sh` paints the whole clip, so the page is covered by the gradient.
    let raster = render(pdf_with(RED_TO_BLUE, "/Sh0 sh"));

    let (r, _, b, a) = pixel(&raster, 1, 50);
    assert_eq!(a, 255, "the shading must be opaque where it paints");
    assert!(
        r > 240 && b < 15,
        "the left edge should be red, got {r},{b}"
    );

    let (r, _, b, _) = pixel(&raster, 98, 50);
    assert!(
        r < 15 && b > 240,
        "the right edge should be blue, got {r},{b}"
    );

    // Halfway along, both components should be near half. This is what catches a
    // gradient that runs the right way but with the wrong parameterisation.
    let (r, _, b, _) = pixel(&raster, 50, 50);
    assert!(
        (100..=155).contains(&r) && (100..=155).contains(&b),
        "the middle should be halfway between, got {r},{b}"
    );
}

/// The axis is a direction, not just a pair of endpoints.
#[test]
fn an_axial_shading_is_constant_perpendicular_to_its_axis() {
    let raster = render(pdf_with(RED_TO_BLUE, "/Sh0 sh"));
    let top = pixel(&raster, 30, 5);
    let bottom = pixel(&raster, 30, 95);
    assert_eq!(
        top, bottom,
        "colour must not vary along the axis's perpendicular"
    );
}

/// `/Extend false` must paint nothing beyond the axis, not the end colour.
///
/// This is the difference between a band and a wash, and it is invisible in a rendered
/// page unless you know what the document asked for.
#[test]
fn a_shading_that_does_not_extend_paints_nothing_beyond_its_ends() {
    let banded = "<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [40 0 60 0] \
                  /Extend [false false] \
                  /Function << /FunctionType 2 /Domain [0 1] \
                  /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";
    let raster = render(pdf_with(banded, "/Sh0 sh"));

    // Inside the band the shading paints.
    assert_eq!(pixel(&raster, 50, 50).3, 255, "the band itself must paint");
    // Outside it, nothing: the page stays as it was.
    assert_eq!(
        pixel(&raster, 5, 50).3,
        0,
        "nothing may be painted before the axis starts"
    );
    assert_eq!(
        pixel(&raster, 95, 50).3,
        0,
        "nothing may be painted after the axis ends"
    );

    // And with extension the same shading covers the page.
    let extended = banded.replace("/Extend [false false]", "/Extend [true true]");
    let raster = render(pdf_with(&extended, "/Sh0 sh"));
    assert_eq!(
        pixel(&raster, 5, 50).3,
        255,
        "extension must reach the edge"
    );
    assert_eq!(pixel(&raster, 95, 50).3, 255);
}

/// ISO 32000-2 §8.7.4.5.2: a type 1 shading marks its transformed domain and nothing else.
///
/// > The transformation matrix ( Matrix ) then maps the domain rectangle into a
/// > corresponding rectangle or parallelogram in the target coordinate space. Points wi thin
/// > the shading's bounding box ( BBox ) that fall outside this transformed domain rectangle
/// > shall be painted with the shading's background colour ( Background ); if the shading
/// > dictionary has no Background entry, such points shall be left unpainted.
///
/// **"Or parallelogram" is the sentence.** The pair below is one shading under two matrices —
/// a 45-degree rotation, and a scale covering the page — so the only thing that differs is
/// where the domain lands. Under the rotation the page's corners are outside it and must stay
/// unpainted; under the scale the same corner is inside and must be painted.
///
/// `function_based_shading.pdf` states `/Matrix [85 85 -85 85 515 382]` and this reader drew
/// a square where four references drew a diamond, inside an `ambiguous` verdict, for the
/// project's whole life. ADR 0150.
#[test]
fn a_function_based_shadings_domain_is_a_parallelogram_and_marks_nothing_outside_it() {
    // A 2-in function has to be a stream, so it goes in as an extra object and the shading
    // names it: `{ pop }` leaves the first input, which is grey enough for an alpha test.
    let function = "7 0 obj\n<< /FunctionType 4 /Domain [0 1 0 1] /Range [0 1] /Length 7 >>\n\
                    stream\n{ pop }\nendstream\nendobj\n";
    let rotated = "<< /ShadingType 1 /ColorSpace /DeviceGray /Domain [0 1 0 1] \
                   /Matrix [35 35 -35 35 50 15] /Function 7 0 R >>";
    let whole_page = "<< /ShadingType 1 /ColorSpace /DeviceGray /Domain [0 1 0 1] \
                      /Matrix [100 0 0 100 0 0] /Function 7 0 R >>";

    let raster = render(pdf_with_extra(rotated, "/Sh0 sh", function));
    assert_eq!(
        pixel(&raster, 50, 50).3,
        255,
        "the middle of the diamond is inside the domain and must paint"
    );
    for corner in [(5, 5), (95, 5), (5, 95), (95, 95)] {
        assert_eq!(
            pixel(&raster, corner.0, corner.1).3,
            0,
            "the page corner at {corner:?} is outside the rotated domain and must stay \
             unpainted"
        );
    }

    let raster = render(pdf_with_extra(whole_page, "/Sh0 sh", function));
    for corner in [(5, 5), (95, 5), (5, 95), (95, 95)] {
        assert_eq!(
            pixel(&raster, corner.0, corner.1).3,
            255,
            "under a matrix covering the page the same corner {corner:?} is inside the \
             domain and must paint"
        );
    }
}

/// ISO 32000-2 §8.7.4.5.2: a type 1 shading's colour is the function's, at every point.
///
/// > In Type 1 (function-based) shadings, the colour at every point in the domain is
/// > defined by a specified mathematical function. The function need not be smooth or
/// > continuous.
///
/// The function here is exactly the discontinuity that sentence licenses — red below
/// `x = 0.5`, blue at and above it — drawn across 400 device pixels, so the step falls at
/// device x = 200. Resolved at the device's grid, each pixel carries the function's value
/// at its own centre: column 199 (centre 199.5, domain 0.49875) is pure red and column 200
/// (centre 200.5, domain 0.50125) pure blue. The 128-cell grid the display list used to
/// carry put a sample every 3.15 device pixels and interpolated between the pair
/// straddling the step, so both of those columns were mixtures — the two constructions
/// cannot be confused, and this walks the whole route: file, interpreter, display list,
/// backend.
#[test]
fn a_function_based_shadings_discontinuity_lands_at_the_device_pixel() {
    // `pop` discards y; `0.5 lt` asks whether x is below the step.
    let function = "7 0 obj\n<< /FunctionType 4 /Domain [0 1 0 1] /Range [0 1 0 1 0 1] \
                    /Length 42 >>\n\
                    stream\n{ pop 0.5 lt { 1 0 0 } { 0 0 1 } ifelse }\nendstream\nendobj\n";
    let shading = "<< /ShadingType 1 /ColorSpace /DeviceRGB /Domain [0 1 0 1] \
                   /Matrix [100 0 0 100 0 0] /Function 7 0 R >>";
    let raster = render_at(pdf_with_extra(shading, "/Sh0 sh", function), 4.0);

    // Columns either side of the step, well inside the page vertically.
    let (r, g, b, a) = pixel(&raster, 199, 200);
    assert_eq!(a, 255, "the domain covers this pixel");
    assert!(
        r >= 253 && g <= 2 && b <= 2,
        "device column 199's centre is at domain 0.49875, below the step, so the clause \
         makes it pure red; a grid fixed at 128 cells interpolates 35% of blue in here. \
         Got ({r}, {g}, {b})"
    );
    let (r, _, b, _) = pixel(&raster, 200, 200);
    assert!(
        b >= 253 && r <= 2,
        "device column 200's centre is at domain 0.50125, at the step and past it, so the \
         clause makes it pure blue. Got ({r}, _, {b})"
    );

    // And away from the step both regimes agree, which pins the colours themselves.
    assert_eq!(pixel(&raster, 100, 200), (255, 0, 0, 255));
    assert_eq!(pixel(&raster, 300, 200), (0, 0, 255, 255));
}

/// Dividing the grid across threads changes no pixel of it (ADR 0364).
///
/// A cell of §8.7.4.5.2's grid is a function of its own two coordinates and of nothing else, so
/// a row boundary decides which thread evaluates a cell and never what the cell evaluates to.
/// That is an argument, and this is the check: the same page drawn with the grid divided and
/// with it whole, compared byte for byte.
///
/// The two arms are chosen by where the caller stands rather than by a knob. A pool of one puts
/// `install`'s closure **on a rayon worker**, which is where `shading::rows_in_parallel`
/// declines — `render-cpu` calls this from inside its own strips and must not fork again — so
/// the whole grid runs in one loop there. The default arm runs on the test's own thread, off
/// the pool, at 200 × 200 cells: above the threshold, so it divides. One strip in both, so that
/// the only difference between them is the one being asked about.
#[test]
fn a_function_based_shadings_grid_is_the_same_however_it_is_divided() {
    // Varies in both axes, so a row taken by the wrong thread would show as a shifted band.
    let function = "7 0 obj\n<< /FunctionType 4 /Domain [0 1 0 1] /Range [0 1 0 1 0 1] \
                    /Length 43 >>\n\
                    stream\n{ 2 copy add 2 div 3 1 roll sub abs exch }\nendstream\nendobj\n";
    let shading = "<< /ShadingType 1 /ColorSpace /DeviceRGB /Domain [0 1 0 1] \
                   /Matrix [200 0 0 200 0 0] /Function 7 0 R >>";
    let bytes = pdf_with_extra(shading, "/Sh0 sh", function);

    let draw = |source: Vec<u8>| {
        let document = Document::open(source).expect("the fixture is a valid PDF");
        let page = pdf_model::Pages::new(&document).get(0).expect("page one");
        let list = pdf_model::interpret(&document, &page).display_list;
        let target = TargetSpec::for_page(&list, 1.0, GENEROUS).expect("valid target");
        CpuRasterizer::new()
            .with_strips(1)
            .rasterize(&list, target)
            .expect("supported")
    };

    let divided = draw(bytes.clone());
    let pool = rayon::ThreadPoolBuilder::new()
        .num_threads(1)
        .build()
        .expect("a pool of one");
    let whole = pool.install(|| draw(bytes));

    assert_eq!(
        divided.data, whole.data,
        "the grid divided across rows and the grid evaluated in one loop are the same picture"
    );
    // And it is a picture rather than a blank page, or the comparison above is vacuous.
    assert!(
        divided.data.chunks_exact(4).any(|p| p[0] != p[2]),
        "the function varies across the domain, so red and blue differ somewhere"
    );
}

/// A radial shading with two different radii, which is PDF's general case.
#[test]
fn a_radial_shading_grades_between_its_two_circles() {
    let radial = "<< /ShadingType 3 /ColorSpace /DeviceRGB /Coords [50 50 0 50 50 40] \
                  /Extend [false false] \
                  /Function << /FunctionType 2 /Domain [0 1] \
                  /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";
    let raster = render(pdf_with(radial, "/Sh0 sh"));

    // The centre is the inner circle's colour.
    let (r, _, b, a) = pixel(&raster, 50, 50);
    assert_eq!(a, 255);
    assert!(r > 240 && b < 15, "the centre should be red, got {r},{b}");

    // Just inside the outer circle is the outer colour.
    let (r, _, b, _) = pixel(&raster, 50, 12);
    assert!(r < 60 && b > 200, "the rim should be blue, got {r},{b}");

    // Outside it, nothing, because the shading does not extend.
    assert_eq!(
        pixel(&raster, 50, 2).3,
        0,
        "a non-extended radial must not paint beyond its outer circle"
    );

    // The gradient is radial, so points equidistant from the centre must match.
    assert_eq!(pixel(&raster, 50, 30), pixel(&raster, 30, 50));
}

/// A shading used as a fill colour through a pattern, rather than by `sh`.
#[test]
fn a_shading_pattern_fills_only_the_path_it_paints() {
    // Fill the left half of the page with the pattern.
    let content = "/Pattern cs /P0 scn 0 0 50 100 re f";
    let raster = render(pdf_with(RED_TO_BLUE, content));

    // Inside the filled rectangle the gradient shows.
    let (r, _, b, a) = pixel(&raster, 2, 50);
    assert_eq!(a, 255, "the pattern must paint inside the path");
    assert!(r > 230 && b < 25, "and carry the shading's colour: {r},{b}");

    // The pattern is positioned in page space, so the colour at x is the same as it
    // would be under `sh` — the fill shapes it but does not move it.
    let (pattern_r, ..) = pixel(&raster, 40, 50);
    let direct = render(pdf_with(RED_TO_BLUE, "/Sh0 sh"));
    let (direct_r, ..) = pixel(&direct, 40, 50);
    assert!(
        pattern_r.abs_diff(direct_r) <= 1,
        "a pattern must not shift the shading: {pattern_r} against {direct_r}"
    );

    // Outside the path, nothing.
    assert_eq!(
        pixel(&raster, 80, 50).3,
        0,
        "a pattern fill must not escape its path"
    );
}

/// §8.7.4.3 Table 77's `/BBox` clips the shading, by `sh` and through a pattern alike.
///
/// > If present, this bounding box shall be applied as a temporary clipping boundary when
/// > the shading is painted, in addition to the current clipping path and any other clipping
/// > boundaries in effect at that time.
///
/// "In addition to" is the load-bearing phrase and the reason the box nests inside the
/// state's clip rather than replacing it. The other half — "the coordinates shall be
/// interpreted in the shading's target coordinate space" — is what decides *which* transform
/// carries it: the space the caller paints into, which for `sh` is the current user space
/// and for a pattern is the pattern space.
///
/// Five corpus documents write a shading `/BBox` and **not one of them changes by a pixel**,
/// because in every case the box is at least as large as the path or page the shading was
/// already confined to. So the clause has no witness in 974 documents and this fixture is
/// the whole of what defends it — trap 8's shape, again.
#[test]
fn a_shadings_bbox_clips_what_it_paints() {
    let bounded = "<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [0 0 100 0] \
                   /BBox [0 0 40 100] \
                   /Function << /FunctionType 2 /Domain [0 1] /C0 [1 0 0] /C1 [0 0 1] \
                   /N 1 >> >>";

    // `sh` covers the page, so the box is the only thing that can stop it.
    let raster = render(pdf_with(bounded, "/Sh0 sh"));
    assert_eq!(
        pixel(&raster, 20, 50).3,
        255,
        "inside the /BBox the shading paints"
    );
    assert_eq!(
        pixel(&raster, 60, 50).3,
        0,
        "beyond the /BBox it must not, however far the gradient reaches"
    );

    // Through a pattern, filling a rectangle that extends past the box in both directions:
    // the painted region is the intersection, which is what "in addition to" means.
    let raster = render(pdf_with(bounded, "/Pattern cs /P0 scn 20 0 60 100 re f"));
    assert_eq!(
        pixel(&raster, 10, 50).3,
        0,
        "outside the filled path, nothing — the box does not widen the fill"
    );
    assert_eq!(
        pixel(&raster, 30, 50).3,
        255,
        "inside both, the shading paints"
    );
    assert_eq!(
        pixel(&raster, 60, 50).3,
        0,
        "inside the path but outside the box, nothing"
    );
}

/// §8.7.4.3 Table 77's `/Background` is not painted, and the clause's own condition decides
/// where that is worth saying.
///
/// > If present, this colour shall be used, before any painting operation involving the
/// > shading, to fill those portions of the area to be painted that lie outside the bounds of
/// > the shading object.
///
/// and, in the same cell:
///
/// > The background colour shall be applied only when the shading is used as part of a shading
/// > pattern, not when painted directly with the sh operator.
///
/// So a `sh` that states one owes nothing and reports nothing, and a *pattern* that states one
/// is a mark this tree does not make. Both halves are asserted here, because a report raised on
/// the wrong one of the two would be noise on every page that paints a shading directly.
/// `doc/todo/17` prices the drawing; the ledger's §8.7.4.3 row carries the population.
#[test]
fn a_shading_patterns_background_is_reported_and_sh_owes_nothing() {
    let with_background = "<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [40 0 60 0] \
                           /Background [0 1 1] \
                           /Function << /FunctionType 2 /Domain [0 1] /C0 [1 0 0] \
                           /C1 [0 0 1] /N 1 >> >>";

    let reported = |content: &str| {
        let bytes = pdf_with(with_background, content);
        let document = Document::open(bytes).expect("the fixture is a valid PDF");
        let page = pdf_model::Pages::new(&document).get(0).expect("page one");
        format!("{:?}", pdf_model::interpret(&document, &page).unsupported)
    };

    let through_a_pattern = reported("/Pattern cs /P0 scn 0 0 100 100 re f");
    assert!(
        through_a_pattern.contains("ShadingBackground")
            && through_a_pattern.contains("/P0")
            && through_a_pattern.contains("3 component(s)"),
        "a pattern's unpainted /Background must be named with its pattern and its length: \
         {through_a_pattern}"
    );

    let directly = reported("/Sh0 sh");
    assert!(
        !directly.contains("ShadingBackground"),
        "`sh` is the case the clause exempts, so it must owe nothing: {directly}"
    );
}

/// Colour spaces are resolved before the display list, so a shading in CMYK must land
/// on the same colours as the equivalent one in RGB.
#[test]
fn a_shading_in_another_colour_space_is_converted() {
    let cmyk = "<< /ShadingType 2 /ColorSpace /DeviceCMYK /Coords [0 0 100 0] \
                /Extend [true true] \
                /Function << /FunctionType 2 /Domain [0 1] \
                /C0 [0 1 1 0] /C1 [1 1 0 0] /N 1 >> >>";
    let raster = render(pdf_with(cmyk, "/Sh0 sh"));

    // Cyan 0, magenta 1, yellow 1 is process red, and cyan 1, magenta 1, yellow 0 is
    // process blue — not the `#FF0000` and `#0000FF` a naive conversion gives. The point
    // of the test is that the shading is converted through the same colour space as
    // everything else, so the values are the ones `colour.rs` pins against the reference
    // renderers, give or take the ramp's own sampling.
    let (r, g, b, _) = pixel(&raster, 1, 50);
    assert!(
        (225..=245).contains(&r) && g < 40 && b < 50,
        "expected process red near (237,28,36), got {r},{g},{b}"
    );
    let (r, g, b, _) = pixel(&raster, 98, 50);
    assert!(
        r < 60 && g < 60 && (135..=160).contains(&b),
        "expected process blue near (46,49,146), got {r},{g},{b}"
    );
}

/// A free-form triangle mesh, whose corner colours must land at its corners.
///
/// The data is written as ASCII hex so the fixture stays readable: a mesh stream is a bit
/// stream of packed coordinates and components, and a binary blob in a test tells the
/// reader nothing about what it is meant to contain.
#[test]
fn a_triangle_mesh_puts_its_corner_colours_at_its_corners() {
    // Eight bits each for the flag, both coordinates and all three components, so every
    // vertex is six whole bytes and needs no padding.
    //
    // Three vertices, each `flag x y r g b`:
    //   (0,0) red, (100,0) green, (0,100) blue — a right triangle filling the lower left.
    //   `/Decode` maps the raw 0..255 range onto 0..100, so `FF` is the far corner.
    let data = "00 00 00 FF 00 00  00 FF 00 00 FF 00  00 00 FF 00 00 FF >";
    let mesh = format!(
        "<< /ShadingType 4 /ColorSpace /DeviceRGB /BitsPerCoordinate 8 \
         /BitsPerComponent 8 /BitsPerFlag 8 /Decode [0 100 0 100 0 1 0 1 0 1] \
         /Filter /ASCIIHexDecode /Length {} >>\nstream\n{data}\nendstream",
        data.len()
    );
    let raster = render(pdf_with(&mesh, "/Sh0 sh"));

    // Well inside each corner, the colour is that corner's.
    let (r, g, b, a) = pixel(&raster, 4, 95);
    assert_eq!(a, 255, "the mesh must paint inside the triangle");
    assert!(
        r > 200 && g < 60 && b < 60,
        "corner one should be red: {r},{g},{b}"
    );

    let (r, g, b, _) = pixel(&raster, 92, 95);
    assert!(
        g > 200 && r < 60 && b < 60,
        "corner two should be green: {r},{g},{b}"
    );

    let (r, g, b, _) = pixel(&raster, 4, 6);
    assert!(
        b > 200 && r < 60 && g < 60,
        "corner three should be blue: {r},{g},{b}"
    );

    // The middle of the triangle is a blend of all three, not any one of them.
    let (r, g, b, _) = pixel(&raster, 30, 62);
    assert!(
        r > 30 && g > 30 && b > 30,
        "the interior should be interpolated, got {r},{g},{b}"
    );

    // Outside the triangle nothing is painted: a mesh covers only its own area, even
    // though `sh` names the whole clip.
    assert_eq!(
        pixel(&raster, 90, 8).3,
        0,
        "a mesh must not paint outside its triangles"
    );
}

/// A lattice mesh (§8.7.4.5.6) fills the quad between two rows, both triangles of it.
///
/// Type 5 states no edge flags at all: the geometry *is* the row structure, so the two
/// triangles between a pair of rows are the whole of what the clause asks a reader to
/// construct. A reader that formed one triangle per cell instead would leave half of every
/// cell unpainted and put three of the four corner colours in the right place all the same,
/// which is why the assertion below is about the fourth corner and about coverage.
#[test]
fn a_lattice_mesh_triangulates_between_its_rows() {
    // No flags, and eight bits each for the coordinates and the three components, so a
    // vertex is five whole bytes. Two rows of two: red and green along the bottom of the
    // page, blue and yellow along the top.
    let data = "00 00 FF 00 00  FF 00 00 FF 00  00 FF 00 00 FF  FF FF FF FF 00 >";
    let mesh = format!(
        "<< /ShadingType 5 /ColorSpace /DeviceRGB /VerticesPerRow 2 /BitsPerCoordinate 8 \
         /BitsPerComponent 8 /Decode [0 100 0 100 0 1 0 1 0 1] \
         /Filter /ASCIIHexDecode /Length {} >>\nstream\n{data}\nendstream",
        data.len()
    );
    let raster = render(pdf_with(&mesh, "/Sh0 sh"));

    // Page (5, 5) is raster row 94: the first row's first vertex, which is red.
    let (r, g, b, a) = pixel(&raster, 5, 94);
    assert_eq!(a, 255, "the lattice paints its own area");
    assert!(
        r > 200 && g < 60 && b < 60,
        "bottom left is red: {r},{g},{b}"
    );
    let (r, g, b, _) = pixel(&raster, 94, 94);
    assert!(
        g > 200 && r < 60 && b < 60,
        "bottom right is green: {r},{g},{b}"
    );
    let (r, g, b, _) = pixel(&raster, 5, 5);
    assert!(b > 200 && r < 60 && g < 60, "top left is blue: {r},{g},{b}");
    // The fourth corner is the one a single triangle per cell would not reach.
    let (r, g, b, a) = pixel(&raster, 94, 5);
    assert_eq!(a, 255, "both triangles of the cell are drawn");
    assert!(
        r > 200 && g > 200 && b < 60,
        "top right is yellow: {r},{g},{b}"
    );
}

/// A mesh with a `/Function` interpolates the parameter, not the colour (§8.7.4.5.5).
///
/// > If the shading dictionary contains a Function entry, the colour data for each vertex
/// > shall be specified by a single parametric value t rather than by n separate colour
/// > components. All linear interpolation within the triangle mesh shall be done using the t
/// > values. After interpolation, the results shall be passed to the function(s) specified in
/// > the Function entry to determine the colour at each point.
///
/// The two orders agree wherever the function is a straight line, which is why this fixture's
/// is `/N 2`: red rises as `t²`. The corners carry `t = 0`, `1` and `0`, so at the pixel
/// sampled below the interpolated parameter is 0.505 and the clause's colour is
/// `0.505² = 0.255` of full red — 65. Evaluating the function at each corner first and
/// interpolating the *colours* gives `0.505` — 129, twice as much, and nothing about the
/// resulting page says which was done. That is what this tree drew until it read the sentence.
#[test]
fn a_mesh_with_a_function_interpolates_the_parameter() {
    // Eight bits each for the flag, both coordinates and the single parametric value, so a
    // vertex is four whole bytes.
    //
    // Three vertices, each `flag x y t`: (0,0) at t = 0, (100,0) at t = 1, (0,100) at t = 0.
    let data = "00 00 00 00  00 FF 00 FF  00 00 FF 00 >";
    let mesh = format!(
        "<< /ShadingType 4 /ColorSpace /DeviceRGB /BitsPerCoordinate 8 \
         /BitsPerComponent 8 /BitsPerFlag 8 /Decode [0 100 0 100 0 1] \
         /Function << /FunctionType 2 /Domain [0 1] /C0 [0 0 0] /C1 [1 0 0] /N 2 >> \
         /Filter /ASCIIHexDecode /Length {} >>\nstream\n{data}\nendstream",
        data.len()
    );
    let raster = render(pdf_with(&mesh, "/Sh0 sh"));

    // Device (50, 95) is page (50.5, 4.5): barycentric 0.505 towards the `t = 1` corner.
    let parameter = 0.505_f32;
    let (red, green, blue, alpha) = pixel(&raster, 50, 95);
    assert_eq!(alpha, 255, "the mesh paints this pixel");
    #[expect(
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        reason = "test code: a fraction of full scale, so the rounded product is in 0..=255"
    )]
    let expected = (parameter * parameter * 255.0).round() as u8;
    assert!(
        red.abs_diff(expected) <= 3,
        "§8.7.4.5.5 calls the function with the interpolated parameter, which is {expected} \
         here; interpolating the corner colours would give 129. Got {red}"
    );
    assert!(
        green < 4 && blue < 4,
        "the function states red alone: {red},{green},{blue}"
    );
}

/// A shading type that does not exist must be reported, not skipped.
#[test]
fn an_unknown_shading_type_is_reported() {
    let bogus = "<< /ShadingType 9 /ColorSpace /DeviceRGB >>";
    let bytes = pdf_with(bogus, "/Sh0 sh");
    let document = Document::open(bytes).expect("valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let interpretation = pdf_model::interpret(&document, &page);

    assert!(
        !interpretation.is_complete(),
        "an unknown shading type must be reported rather than silently skipped"
    );
    let reported = format!("{:?}", interpretation.unsupported);
    assert!(
        reported.contains("shading type 9"),
        "the report should name the type: {reported}"
    );
}

/// A mesh whose stream is truncated must be reported rather than drawn in part.
#[test]
fn a_truncated_mesh_is_reported() {
    // One vertex where three are needed.
    let data = "00 00 00 FF 00 00 >";
    let mesh = format!(
        "<< /ShadingType 4 /ColorSpace /DeviceRGB /BitsPerCoordinate 8 \
         /BitsPerComponent 8 /BitsPerFlag 8 /Decode [0 100 0 100 0 1 0 1 0 1] \
         /Filter /ASCIIHexDecode /Length {} >>\nstream\n{data}\nendstream",
        data.len()
    );
    let bytes = pdf_with(&mesh, "/Sh0 sh");
    let document = Document::open(bytes).expect("valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    assert!(
        !pdf_model::interpret(&document, &page).is_complete(),
        "a mesh with no complete triangle must be reported"
    );
}

/// A `/FunctionType 4` returning `red = x`, `green = y`, `blue = 0` over the unit square.
///
/// The two inputs are already on the stack when the program starts (§7.10.5), so pushing one
/// zero leaves exactly the three values the `/Range` asks for. A two-input function has to be
/// a stream — Table 38's exponential and stitching types take one input each — which is why
/// this is the one fixture here that needs an extra object.
const DOMAIN_AS_COLOUR: &str = "7 0 obj\n<< /FunctionType 4 /Domain [0 1 0 1] \
                                /Range [0 1 0 1 0 1] /Length 5 >>\nstream\n{ 0 }\n\
                                endstream\nendobj\n";

/// ISO 32000-2 §8.7.4.5.2, Table 78: a type 1 shading's `/Matrix` places its domain.
///
/// > Matrix … An array of six numbers specifying a transformation matrix mapping the
/// > coordinate space specified by the Domain entry into the shading's target coordinate
/// > space.
///
/// The function is the identity on the domain, so every pixel names the domain point it came
/// from — which turns "is the matrix applied, and the right way round" into an assertion about
/// two pixels rather than about a gradient's appearance. The second half is the one that
/// discriminates: translating the matrix by half the page must move the colours by half the
/// page, and a reader that ignores `/Matrix` altogether draws the domain's unit square into
/// one point at the page's corner and leaves the rest of it flat.
#[test]
fn a_function_based_shading_maps_its_domain_through_its_matrix() {
    let shading = |matrix: &str| {
        format!(
            "<< /ShadingType 1 /ColorSpace /DeviceRGB /Domain [0 1 0 1] \
             /Matrix {matrix} /Function 7 0 R >>"
        )
    };

    // The domain covers the whole 100x100 page. Device row 0 is the page's *top*, so a
    // device y of 25 is a domain y of 0.75.
    let across = render(pdf_with_extra(
        &shading("[100 0 0 100 0 0]"),
        "/Sh0 sh",
        DOMAIN_AS_COLOUR,
    ));
    let (red, green, blue, alpha) = pixel(&across, 25, 25);
    assert_eq!(alpha, 255, "the shading paints the whole clip");
    assert_eq!(blue, 0, "the function's third output is a constant zero");
    assert!(
        (60..=70).contains(&red),
        "red is the domain's x at a quarter across the page, got {red}"
    );
    assert!(
        (185..=195).contains(&green),
        "green is the domain's y, which is 0.75 a quarter *down* the page, got {green}"
    );

    // The same shading with its domain pushed half a page to the right: the colour a quarter
    // across the page must now be the one that was at the page's left edge.
    let shifted = render(pdf_with_extra(
        &shading("[100 0 0 100 50 0]"),
        "/Sh0 sh",
        DOMAIN_AS_COLOUR,
    ));
    let (shifted_red, _, _, _) = pixel(&shifted, 75, 25);
    assert_eq!(
        shifted_red, red,
        "translating the matrix by half the page moves the colours by half the page"
    );
}

/// An annotation's appearance is a form `XObject`, so its patterns map to *its* default space.
///
/// ISO 32000-2 §8.7.2:
///
/// > Similarly, if a pattern is used within a form XObject (see 8.10, "Form XObjects" ), the
/// > pattern matrix maps pattern space to the form's default user space (that is, the form
/// > coordinate space at the time the form is painted with the Do operator).
///
/// §12.5.5 makes an appearance stream one of those forms, and `content.rs` had the rule on the
/// `Do` path and not on this one — so a shading pattern inside an annotation was positioned by
/// the *page's* default transform. ADR 0160.
///
/// The fixture separates the two spaces the way `issue7821.pdf` does: the appearance draws at
/// x 200–300 and its `/Matrix` brings that back to the page's 0–100. The shading's axis is
/// stated at 200–300, in the appearance's own space, so under the page's transform it would sit
/// entirely off the right edge and `/Extend` would paint the whole box one flat colour. Deleting
/// the `self.base` swap in `draw_appearance` turns both samples below red, which is what
/// establishes that this test guards it.
#[test]
fn a_pattern_in_an_annotation_appearance_is_placed_in_the_appearances_own_space() {
    let body = concat!(
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
        "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
        "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> ",
        "/Annots [5 0 R] /Contents 4 0 R >>\nendobj\n",
        "4 0 obj\n<< /Length 1 >>\nstream\n\nendstream\nendobj\n",
        "5 0 obj\n<< /Type /Annot /Subtype /Stamp /F 4 /Rect [0 0 100 100] ",
        "/AP << /N 6 0 R >> >>\nendobj\n",
        "6 0 obj\n<< /Type /XObject /Subtype /Form /BBox [200 200 300 300] ",
        "/Matrix [1 0 0 1 -200 -200] /Resources << /Pattern << /P0 7 0 R >> >> ",
        "/Length 42 >>\nstream\n/Pattern cs /P0 scn 200 200 100 100 re f\nendstream\nendobj\n",
        "7 0 obj\n<< /PatternType 2 /Shading 8 0 R >>\nendobj\n",
        "8 0 obj\n<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [200 0 300 0] ",
        "/Extend [true true] /Function << /FunctionType 2 /Domain [0 1] ",
        "/C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>\nendobj\n",
    );
    let raster = render(assemble(body));

    let (left_red, _, left_blue, alpha) = pixel(&raster, 5, 50);
    assert_eq!(alpha, 255, "the appearance fills its whole box");
    let (right_red, _, right_blue, _) = pixel(&raster, 95, 50);
    assert!(
        left_red > 220 && left_blue < 40,
        "the axis starts red at the box's left edge, got ({left_red}, _, {left_blue})"
    );
    assert!(
        right_blue > 220 && right_red < 40,
        "and ends blue at its right edge, got ({right_red}, _, {right_blue})"
    );
}

/// §7.10.5.1 admits comments, so a commented program and a bare one are one function.
///
/// > This subset is comprised of the following PostScript language features: … Comments
///
/// The two arms are written out separately in `test-scenes` and differ in nothing else, so
/// anything but an identical raster is the compiler reading a comment as code. It did until the
/// five-hundred-and-twenty-sixth session, and both shapes are in the commented arm: a prose
/// comment, which was refused outright, and one quoting a formula (`% dup 3 mul`), whose words
/// were compiled into the program with nothing reported.
///
/// The ink is asserted as well as the equality, because two arms that both refused to draw
/// would also be identical — which is exactly what the old code did to the loud shape.
#[test]
fn a_type_4_program_paints_the_same_page_with_and_without_its_comments() {
    let commented = render(type4_comment_pair(Type4Comments::Present));
    let bare = render(type4_comment_pair(Type4Comments::Absent));

    assert_eq!(
        (commented.width, commented.height),
        (bare.width, bare.height)
    );
    assert_eq!(
        commented.data, bare.data,
        "a comment changed what the function computes"
    );

    // What the program says: black left of the split, white right of it.
    let (width, height) = TYPE4_PAGE;
    assert_eq!((commented.width, commented.height), (width, height));
    let middle = height / 2;
    for raster in [&commented, &bare] {
        assert_eq!(
            pixel(raster, TYPE4_SPLIT / 2, middle),
            (0, 0, 0, 255),
            "x below the split is 0, which is black"
        );
        assert_eq!(
            pixel(raster, TYPE4_SPLIT + TYPE4_SPLIT / 2, middle),
            (255, 255, 255, 255),
            "x above the split is 1, which is white"
        );
    }
}

/// The project owner's `doc/corpora-own/type4_pi.pdf`, which is what found the defect.
///
/// A §7.10.5 program that computes π by the first two terms of the BBP series and paints its
/// digits as rectangles, hand-written with a comment above every step. Before the
/// five-hundred-and-twenty-sixth session the whole shading was refused — `% BBP Math for Pi …`
/// left `Math` looking like an operator — so the page came out blank with one report.
///
/// The rectangles the program tests are its own comments' (`% Rect 10,25 85,95` is x ∈ [10, 25],
/// y ∈ [85, 95] on a 0–100 square that `/Matrix` scales onto the 400-point page), and together
/// they spell `3.141`: three bars and a stem, a full stop, a stem, a four, a stem. The samples
/// below are the centres of five of them and three points of the background between them, so
/// this fails on a page that is blank, inverted, mirrored or shifted.
#[test]
fn the_owners_pi_file_paints_the_digits_its_program_computes() {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../doc/corpora-own/type4_pi.pdf");
    let bytes = std::fs::read(&path).expect("the witness is tracked in this repository");
    let raster = render(bytes);

    // The program's square is 0–100 in both axes over a 400-point page, and the raster's y runs
    // the other way from the page's: pixel = (4x, 400 − 4y).
    let at = |x: u32, y: u32| {
        pixel(
            &raster,
            x.saturating_mul(4),
            400_u32.saturating_sub(y.saturating_mul(4)),
        )
    };

    for (x, y, what) in [
        (17, 90, "the top bar of the 3"),
        (30, 10, "the full stop"),
        (44, 50, "the 1"),
        (65, 50, "the 4's crossbar"),
        (86, 50, "the last 1"),
    ] {
        assert_eq!(
            at(x, y),
            (0, 0, 0, 255),
            "{what} is inside the shape: black"
        );
    }
    for (x, y, what) in [
        (5, 50, "left of the 3"),
        (36, 50, "between the full stop and the 1"),
        (95, 50, "right of the last 1"),
    ] {
        assert_eq!(
            at(x, y),
            (255, 255, 255, 255),
            "{what} is background: white"
        );
    }
}

/// π itself, which the picture above cannot state: the value the file's own comment claims.
///
/// The program's arithmetic is the BBP series' first two terms, and it is quoted here with the
/// comment that made the file fail. 4/1 − 2/4 − 1/5 − 1/6 = 3.13333…, plus
/// (4/9 − 2/12 − 1/13 − 1/14)/16 = 0.0080891…, is 3.1414224… — within 2 × 10⁻⁴ of π — and the
/// program's own `1000 mul truncate 1000 div` is what makes that the exact 3.141 its comment
/// promises. `/Range` is stated wide enough to carry it, since §7.10.5.3 clips the output to it.
#[test]
#[expect(
    clippy::approx_constant,
    reason = "3.141 is the truncation the program performs, not a stand-in for π: the whole \
              point is that the file's own comment claims this value and the picture spells it"
)]
fn the_owners_bbp_series_evaluates_to_pi_to_three_places() {
    let program = "{ pop\n\
         % BBP Math for Pi (leaves 3.141 on stack)\n\
         4 1 div 2 4 div sub 1 5 div sub 1 6 div sub\n\
         4 9 div 2 12 div sub 1 13 div sub 1 14 div sub 16 div\n\
         add 1000.0 mul truncate 1000.0 div\n\
         }";
    let body = format!(
        "1 0 obj\n<< /FunctionType 4 /Domain [0 1] /Range [0 10] /Length {} >>\n\
         stream\n{program}\nendstream\nendobj\n",
        program.len().saturating_add(1)
    );
    let mut source = String::from("%PDF-1.7\n");
    source.push_str(&body);
    source.push_str("trailer\n<< /Root 1 0 R >>\n");

    let document = Document::open(source.into_bytes()).expect("opens");
    let object = pdf_syntax::Object::Reference(pdf_syntax::ObjectId {
        number: 1,
        generation: 0,
    });
    let function =
        pdf_model::function::Function::parse(&document, &object).expect("the program compiles");

    assert_eq!(function.eval(&[0.0]), vec![3.141]);
}

/// A clipped block of §8.7.4.5.2's grid carries the *same bits* as the whole grid's cells.
///
/// ADR 0408 clips the grid to the part of the domain a target can sample, which is only worth
/// having if it is exact: a shading whose colours shifted at a zoom boundary would be far
/// worse than a slow one. The clause's own sentence is why the bar is bits rather than levels
/// — "[t]he function need not be smooth or continuous" — and the function below is exactly
/// such a discontinuity, so a sample that moved across the step is a whole unit of colour
/// rather than a rounding.
///
/// The guarantee is structural: a cell's centre is decided by its index in the *lattice*, and
/// the lattice is `Patch::grid` whatever block is asked for. This walks a ladder of blocks
/// against the whole grid and compares `f32::to_bits` of every channel, because `==` hides a
/// `-0.0` where a `0.0` was — ADR 0406's own reason for comparing bit patterns.
#[test]
fn a_clipped_grid_is_the_whole_grids_cells_bit_for_bit() {
    // Discontinuous in x at 0.5 and continuous in y, so a block that moved a sample either
    // side of the step shows as a whole unit and one that moved it elsewhere shows as an ulp.
    let function = "7 0 obj\n<< /FunctionType 4 /Domain [0 1 0 1] /Range [0 1 0 1 0 1] \
                    /Length 49 >>\n\
                    stream\n{ exch 0.5 lt { 1 0 } { 0 1 } ifelse 3 2 roll }\nendstream\nendobj\n";
    let shading = "<< /ShadingType 1 /ColorSpace /DeviceRGB /Domain [0 1 0 1] \
                   /Matrix [100 0 0 100 0 0] /Function 7 0 R >>";

    let document = Document::open(pdf_with_extra(shading, "/Sh0 sh", function))
        .expect("the fixture is a valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let list = pdf_model::interpret(&document, &page).display_list;
    let source = list
        .commands()
        .iter()
        .find_map(|command| match command {
            pdf_render::Command::Fill {
                paint: pdf_render::Paint::Shading(shading),
                ..
            } => match shading.kind.as_ref() {
                pdf_render::ShadingKind::Sampled { source, .. } => Some(source.clone()),
                _ => None,
            },
            _ => None,
        })
        .expect("the page paints one type 1 shading");

    let lattice = pdf_render::Grid {
        width: 137,
        height: 91,
    };
    let whole = source.colours(pdf_render::Patch::whole(lattice));
    assert_eq!((whole.width, whole.height), (lattice.width, lattice.height));
    #[expect(
        clippy::float_cmp,
        reason = "the domain here is [0 1 0 1] and an unclipped block takes its bounds \
                  verbatim rather than computing them, which is the property being checked"
    )]
    {
        assert!(
            whole.covers == [0.0, 1.0, 0.0, 1.0],
            "an unclipped grid covers its whole domain, stated by the domain's own numbers"
        );
    }

    // Blocks against each edge, one in the middle, one straddling the step, and one narrower
    // than the margin the filter asks for.
    for within in [
        [0.0, 0.25, 0.0, 0.25],
        [0.4, 0.6, 0.4, 0.6],
        [0.75, 1.0, 0.75, 1.0],
        [0.49, 0.51, 0.0, 1.0],
        [0.5, 0.5, 0.5, 0.5],
    ] {
        let block = source.colours(pdf_render::Patch {
            grid: lattice,
            within,
        });
        // Where the block sits in the lattice, read back from the rectangle it says it
        // covers — which is the only thing a backend has to place it by.
        #[expect(
            clippy::cast_possible_truncation,
            clippy::cast_sign_loss,
            clippy::cast_precision_loss,
            reason = "a fraction of the unit domain times a lattice this test states, both \
                      small integers"
        )]
        let first = |edge: f32, cells: u32| (edge * cells as f32).round() as u32;
        let left = first(block.covers[0], lattice.width);
        let top = first(block.covers[2], lattice.height);
        assert!(
            left + block.width <= lattice.width && top + block.height <= lattice.height,
            "the block {within:?} sits inside the lattice"
        );
        assert!(
            block.width * block.height < lattice.width * lattice.height,
            "a block of part of the domain is smaller than the whole grid; {within:?} \
             asked for {} × {}",
            block.width,
            block.height
        );

        let bits = |colour: pdf_render::Color| {
            [
                colour.r.to_bits(),
                colour.g.to_bits(),
                colour.b.to_bits(),
                colour.a.to_bits(),
            ]
        };
        for row in 0..block.height {
            for column in 0..block.width {
                let here = block.pixels[(row * block.width + column) as usize];
                let there = whole.pixels[((top + row) * lattice.width + left + column) as usize];
                assert_eq!(
                    bits(here),
                    bits(there),
                    "block {within:?} cell ({column}, {row}) is lattice cell ({}, {}) and \
                     must carry the same bits",
                    left + column,
                    top + row
                );
            }
        }
    }
}

/// The picture a window draws of a magnified page is the picture the whole page has in it.
///
/// The end of ADR 0408's argument, one level above the cells: the same display list at the
/// same magnification, drawn once into a raster of the whole page — where the domain is
/// entirely on the target and nothing is clipped away — and once into a window-sized target
/// whose transform differs only by an integer translation, where most of the domain is off
/// the target and the grid is a block. The window's pixels must be the whole page's, byte for
/// byte, and the offset is an integer so that "the same pixel" means something.
///
/// # Every constant below is chosen so that removing the margin fails this test
///
/// The margin `pdf_render::Patch::within` states is what this really exercises, and a test
/// that merely *renders a window* does not exercise it at all — at one cell per device pixel
/// the cell centres coincide with the pixel centres, the bilinear filter's second weight is
/// zero, and a block cut exactly to the target draws the same page. Three things together
/// make the filter reach past the block's edge:
///
/// - **A magnification at which the budget bites.** `MAX_FUNCTION_CELLS` halves the lattice
///   above 2²² cells, and 100 units at 24× is 2400 × 2400 device pixels, so the lattice is
///   1200 × 1200 and one cell is two device pixels. Now the filter genuinely interpolates.
/// - **An offset that puts the block's first cell on a whole cell.** 1200 device pixels is
///   unit 0.5 is lattice cell 600 exactly, so the window's first column samples at cell
///   600.25 and reads cells 599 and 600 — and 599 is outside a block cut without a margin.
/// - **A discontinuity there.** The function steps from red to blue at domain x = 0.5, which
///   is that very boundary, so the tap that a clipped block would lose is a whole colour
///   away rather than a level. A smooth function hides this: over 1200 cells its neighbours
///   differ by a fifth of a level and every rounding absorbs it.
///
/// Checked by deleting the margin: 151 pixels — one whole column of the window — differ.
#[test]
fn a_window_of_a_magnified_page_draws_what_the_whole_page_has_there() {
    /// The magnification: past what fits the window below, and past where the cell budget
    /// halves the lattice — see the note above on why both are needed.
    const ZOOM: f32 = 24.0;
    /// The window, in device pixels.
    const WINDOW: (u32, u32) = (137, 151);
    /// Where its top-left corner sits in the magnified page, in whole device pixels: the
    /// domain's own half-way point, which is a whole lattice cell and the function's step.
    const OFFSET: (u32, u32) = (1200, 1200);

    // Red below domain x = 0.5 and blue at and above it, which is the step the margin has to
    // carry across the window's own left edge; green rises with y so a block placed a row out
    // shows as well.
    let function = "7 0 obj\n<< /FunctionType 4 /Domain [0 1 0 1] /Range [0 1 0 1 0 1] \
                    /Length 49 >>\n\
                    stream\n{ exch 0.5 lt { 1 0 } { 0 1 } ifelse 3 2 roll }\nendstream\nendobj\n";
    let shading = "<< /ShadingType 1 /ColorSpace /DeviceRGB /Domain [0 1 0 1] \
                   /Matrix [100 0 0 100 0 0] /Function 7 0 R >>";
    let bytes = pdf_with_extra(shading, "/Sh0 sh", function);

    let document = Document::open(bytes).expect("the fixture is a valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let list = pdf_model::interpret(&document, &page).display_list;
    let whole_page = TargetSpec::for_page(&list, ZOOM, GENEROUS).expect("valid target");
    #[expect(
        clippy::cast_precision_loss,
        reason = "an offset of a hundred device pixels, which f32 holds exactly"
    )]
    let window = TargetSpec {
        width: WINDOW.0,
        height: WINDOW.1,
        transform: whole_page.transform.then(pdf_render::Transform::translate(
            -(OFFSET.0 as f32),
            -(OFFSET.1 as f32),
        )),
    };

    let draw = |target| {
        CpuRasterizer::new()
            .with_medium(pdf_render::Medium::NONE)
            .rasterize(&list, target)
            .expect("supported")
    };
    let everything = draw(whole_page);
    let cropped = draw(window);

    let mut differing = 0usize;
    for row in 0..WINDOW.1 {
        for column in 0..WINDOW.0 {
            let there = pixel(&everything, column + OFFSET.0, row + OFFSET.1);
            if pixel(&cropped, column, row) != there {
                differing += 1;
            }
        }
    }
    assert_eq!(
        differing,
        0,
        "a window of the magnified page must be the magnified page's own pixels; {differing} \
         of {} differ",
        WINDOW.0 * WINDOW.1
    );
    // And it is a picture rather than a blank window, or the comparison above is vacuous.
    assert!(
        cropped
            .data
            .chunks_exact(4)
            .any(|p| p[3] == 255 && p[0] != p[2]),
        "the shading paints this window in colours that vary"
    );
}
