//! Shadings, checked by the colour they actually put on the page.
//!
//! A shading is one of the few things whose correctness can be stated exactly: at a known
//! point it must be a known colour. That makes these tests worth more than an eye can
//! give — a gradient running the wrong way, or extending where it should stop, looks
//! entirely plausible in a rendered page and is obvious against a numeric expectation.

#![expect(
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "test code: a malformed fixture or an out-of-range pixel should fail loudly, \
              and the fixtures are small enough that no index can overflow"
)]

use std::fmt::Write as _;

use pdf_render::{Rasterizer, TargetSpec};
use pdf_syntax::Document;
use render_cpu::CpuRasterizer;

/// Pixel budget, far above the small pages these tests build.
const GENEROUS: u64 = 1 << 30;

/// Assembles a one-page PDF around a content stream and some extra objects.
///
/// Written out by hand rather than through a builder so the fixture is readable as PDF:
/// what is being tested is our reading of the format, and a fixture generated by our own
/// code would share any misunderstanding.
fn pdf_with(shading: &str, content: &str) -> Vec<u8> {
    let body = format!(
        "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n\
         2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n\
         3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] \
         /Resources << /Shading << /Sh0 5 0 R >> /Pattern << /P0 6 0 R >> >> \
         /Contents 4 0 R >>\nendobj\n\
         4 0 obj\n<< /Length {} >>\nstream\n{content}\nendstream\nendobj\n\
         5 0 obj\n{shading}\nendobj\n\
         6 0 obj\n<< /PatternType 2 /Shading 5 0 R >>\nendobj\n",
        content.len().saturating_add(1)
    );

    let mut out = String::from("%PDF-1.7\n");
    let mut offsets = Vec::new();
    for object in body.split_inclusive("endobj\n") {
        offsets.push(out.len());
        out.push_str(object);
    }
    let xref_at = out.len();
    let size = offsets.len().saturating_add(1);
    let _ = writeln!(out, "xref\n0 {size}");
    out.push_str("0000000000 65535 f \n");
    for offset in &offsets {
        let _ = writeln!(out, "{offset:010} 00000 n ");
    }
    let _ = write!(
        out,
        "trailer\n<< /Size {size} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    );
    out.into_bytes()
}

/// Renders a fixture at one pixel per unit and returns the pixels.
fn render(bytes: Vec<u8>) -> pdf_render::Raster {
    let document = Document::open(bytes).expect("the fixture is a valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let interpretation = pdf_model::interpret(&document, &page);
    assert!(
        interpretation.is_complete(),
        "the fixture should draw completely: {:?}",
        interpretation.unsupported
    );
    let list = interpretation.display_list;
    let target = TargetSpec::for_page(&list, 1.0, GENEROUS).expect("valid target");
    // A transparent background, so that alpha says exactly whether anything was painted.
    // The default white one would make every pixel opaque and every such assertion
    // vacuous — which is how the first draft of these tests managed to pass while
    // checking nothing.
    CpuRasterizer::new()
        .with_background(pdf_render::Color::TRANSPARENT)
        .rasterize(&list, target)
        .expect("supported")
}

/// The colour at a pixel, as `(r, g, b, a)`.
fn pixel(raster: &pdf_render::Raster, x: u32, y: u32) -> (u8, u8, u8, u8) {
    let at = ((y.saturating_mul(raster.width)).saturating_add(x) as usize).saturating_mul(4);
    (
        raster.data[at],
        raster.data[at + 1],
        raster.data[at + 2],
        raster.data[at + 3],
    )
}

/// A red-to-blue axial shading running left to right across the page.
const RED_TO_BLUE: &str = "<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [0 0 100 0] \
                           /Extend [true true] \
                           /Function << /FunctionType 2 /Domain [0 1] \
                           /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";

#[test]
fn an_axial_shading_runs_from_its_first_colour_to_its_second() {
    // `sh` paints the whole clip, so the page is covered by the gradient.
    let raster = render(pdf_with(RED_TO_BLUE, "/Sh0 sh"));

    let (r, _, b, a) = pixel(&raster, 1, 50);
    assert_eq!(a, 255, "the shading must be opaque where it paints");
    assert!(
        r > 240 && b < 15,
        "the left edge should be red, got {r},{b}"
    );

    let (r, _, b, _) = pixel(&raster, 98, 50);
    assert!(
        r < 15 && b > 240,
        "the right edge should be blue, got {r},{b}"
    );

    // Halfway along, both components should be near half. This is what catches a
    // gradient that runs the right way but with the wrong parameterisation.
    let (r, _, b, _) = pixel(&raster, 50, 50);
    assert!(
        (100..=155).contains(&r) && (100..=155).contains(&b),
        "the middle should be halfway between, got {r},{b}"
    );
}

/// The axis is a direction, not just a pair of endpoints.
#[test]
fn an_axial_shading_is_constant_perpendicular_to_its_axis() {
    let raster = render(pdf_with(RED_TO_BLUE, "/Sh0 sh"));
    let top = pixel(&raster, 30, 5);
    let bottom = pixel(&raster, 30, 95);
    assert_eq!(
        top, bottom,
        "colour must not vary along the axis's perpendicular"
    );
}

/// `/Extend false` must paint nothing beyond the axis, not the end colour.
///
/// This is the difference between a band and a wash, and it is invisible in a rendered
/// page unless you know what the document asked for.
#[test]
fn a_shading_that_does_not_extend_paints_nothing_beyond_its_ends() {
    let banded = "<< /ShadingType 2 /ColorSpace /DeviceRGB /Coords [40 0 60 0] \
                  /Extend [false false] \
                  /Function << /FunctionType 2 /Domain [0 1] \
                  /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";
    let raster = render(pdf_with(banded, "/Sh0 sh"));

    // Inside the band the shading paints.
    assert_eq!(pixel(&raster, 50, 50).3, 255, "the band itself must paint");
    // Outside it, nothing: the page stays as it was.
    assert_eq!(
        pixel(&raster, 5, 50).3,
        0,
        "nothing may be painted before the axis starts"
    );
    assert_eq!(
        pixel(&raster, 95, 50).3,
        0,
        "nothing may be painted after the axis ends"
    );

    // And with extension the same shading covers the page.
    let extended = banded.replace("/Extend [false false]", "/Extend [true true]");
    let raster = render(pdf_with(&extended, "/Sh0 sh"));
    assert_eq!(
        pixel(&raster, 5, 50).3,
        255,
        "extension must reach the edge"
    );
    assert_eq!(pixel(&raster, 95, 50).3, 255);
}

/// A radial shading with two different radii, which is PDF's general case.
#[test]
fn a_radial_shading_grades_between_its_two_circles() {
    let radial = "<< /ShadingType 3 /ColorSpace /DeviceRGB /Coords [50 50 0 50 50 40] \
                  /Extend [false false] \
                  /Function << /FunctionType 2 /Domain [0 1] \
                  /C0 [1 0 0] /C1 [0 0 1] /N 1 >> >>";
    let raster = render(pdf_with(radial, "/Sh0 sh"));

    // The centre is the inner circle's colour.
    let (r, _, b, a) = pixel(&raster, 50, 50);
    assert_eq!(a, 255);
    assert!(r > 240 && b < 15, "the centre should be red, got {r},{b}");

    // Just inside the outer circle is the outer colour.
    let (r, _, b, _) = pixel(&raster, 50, 12);
    assert!(r < 60 && b > 200, "the rim should be blue, got {r},{b}");

    // Outside it, nothing, because the shading does not extend.
    assert_eq!(
        pixel(&raster, 50, 2).3,
        0,
        "a non-extended radial must not paint beyond its outer circle"
    );

    // The gradient is radial, so points equidistant from the centre must match.
    assert_eq!(pixel(&raster, 50, 30), pixel(&raster, 30, 50));
}

/// A shading used as a fill colour through a pattern, rather than by `sh`.
#[test]
fn a_shading_pattern_fills_only_the_path_it_paints() {
    // Fill the left half of the page with the pattern.
    let content = "/Pattern cs /P0 scn 0 0 50 100 re f";
    let raster = render(pdf_with(RED_TO_BLUE, content));

    // Inside the filled rectangle the gradient shows.
    let (r, _, b, a) = pixel(&raster, 2, 50);
    assert_eq!(a, 255, "the pattern must paint inside the path");
    assert!(r > 230 && b < 25, "and carry the shading's colour: {r},{b}");

    // The pattern is positioned in page space, so the colour at x is the same as it
    // would be under `sh` — the fill shapes it but does not move it.
    let (pattern_r, ..) = pixel(&raster, 40, 50);
    let direct = render(pdf_with(RED_TO_BLUE, "/Sh0 sh"));
    let (direct_r, ..) = pixel(&direct, 40, 50);
    assert!(
        pattern_r.abs_diff(direct_r) <= 1,
        "a pattern must not shift the shading: {pattern_r} against {direct_r}"
    );

    // Outside the path, nothing.
    assert_eq!(
        pixel(&raster, 80, 50).3,
        0,
        "a pattern fill must not escape its path"
    );
}

/// Colour spaces are resolved before the display list, so a shading in CMYK must land
/// on the same colours as the equivalent one in RGB.
#[test]
fn a_shading_in_another_colour_space_is_converted() {
    let cmyk = "<< /ShadingType 2 /ColorSpace /DeviceCMYK /Coords [0 0 100 0] \
                /Extend [true true] \
                /Function << /FunctionType 2 /Domain [0 1] \
                /C0 [0 1 1 0] /C1 [1 1 0 0] /N 1 >> >>";
    let raster = render(pdf_with(cmyk, "/Sh0 sh"));

    // Cyan 0, magenta 1, yellow 1 is red; cyan 1, magenta 1, yellow 0 is blue.
    let (r, g, b, _) = pixel(&raster, 1, 50);
    assert!(r > 240 && g < 15 && b < 15, "expected red, got {r},{g},{b}");
    let (r, g, b, _) = pixel(&raster, 98, 50);
    assert!(
        r < 15 && g < 15 && b > 240,
        "expected blue, got {r},{g},{b}"
    );
}

/// A shading type this crate does not implement must be reported, not skipped.
#[test]
fn an_unimplemented_shading_type_is_reported() {
    let mesh = "<< /ShadingType 4 /ColorSpace /DeviceRGB /BitsPerCoordinate 16 \
                /BitsPerComponent 8 /BitsPerFlag 8 /Decode [0 100 0 100 0 1 0 1 0 1] >>";
    let bytes = pdf_with(mesh, "/Sh0 sh");
    let document = Document::open(bytes).expect("valid PDF");
    let page = pdf_model::Pages::new(&document).get(0).expect("page one");
    let interpretation = pdf_model::interpret(&document, &page);

    assert!(
        !interpretation.is_complete(),
        "an unimplemented shading type must be reported rather than silently skipped"
    );
    let reported = format!("{:?}", interpretation.unsupported);
    assert!(
        reported.contains("shading type 4"),
        "the report should name the type: {reported}"
    );
}
