//! Checks this project's citations of ISO 32000-2, and keeps the conformance ledger.
//!
//! # The problem this solves
//!
//! This tree cited the standard 146 times over 36 distinct clause numbers, and until this
//! crate existed **nothing checked a single citation**. The first tooling ever pointed at
//! them found that two of the 36 name clauses ISO 32000-2 does not have — `§8.9.6.5` and
//! `§11.4.5.6`, each copied from comment to comment and into two written reports — and that
//! three of five quotations sampled by hand were paraphrases inside quotation marks.
//!
//! **The checker is not the part that found the most, and that is worth knowing before
//! trusting it.** Once those four numbers were corrected the citation check went green and
//! has stayed green; what kept producing findings was the *reading* the ledger demands. The
//! corrected `/Mask` citations were still wrong — §8.9.6.2 is stencil masking and `/Mask`
//! naming a second image is §8.9.6.3 — and no index lookup can catch a right-looking number
//! that names the wrong clause. This crate makes the reading routine and records what it
//! found. It does not replace it.
//!
//! None of that had changed a pixel. All of it corrodes what the project runs on: a citation
//! is how a reviewer checks the code against the clause instead of against itself, and this
//! project's best habit — *a subclause is a checklist* — is worth exactly as much as the
//! number attached to it. A reference decays at the rate of the attention paid to it, and
//! here the attention is spent on pixels, correctly. So the references are checked by
//! something that never gets tired.
//!
//! # The two halves
//!
//! - **Citations** ([`citation`], [`clause`], [`quote`]). Every `§` names a clause the
//!   standard has; every rustdoc blockquote is the standard's own words, found within the
//!   clause it is attributed to.
//! - **The ledger** ([`ledger`]). One row per subclause of clauses 7–14, carrying a status a
//!   person set after reading the clause against this code. It is the second denominator:
//!   the corpus and the oracle measure what share of *the files that exist* we draw
//!   correctly, and neither can rank a requirement no file exercises.
//!
//! What the checker verifies is that a claim is well formed and honest — never that the code
//! implements the clause. Only a person reading the clause can establish that, which is why
//! the ledger holds statuses rather than a computed percentage.
//!
//! # Running it
//!
//! The gate is `tests/conformance.rs`, and it runs with the rest of the workspace's tests.
//! The ledger is generated and regenerated by `cargo run -p conformance --bin ledger`, which
//! adds rows for clauses that have none and leaves every existing row untouched.

#![forbid(unsafe_code)]

pub mod citation;
pub mod clause;
pub mod ledger;
pub mod prose;
pub mod quote;
pub mod toml_subset;

use std::path::{Path, PathBuf};

use citation::{Citation, Scan};

/// The standard, in the form code can read.
///
/// **Not tracked in the clear** — ISO's text is free to obtain and not free to redistribute, so
/// the repository carries it inside `doc/specifications.zip` and a developer unpacks it (ADR
/// 0187, `NOTICE` section 3). Without that step every check below fails rather than skipping,
/// which is the cost that decision names and accepts.
pub const STANDARD: &str = "doc/md/ISO_32000-2_sponsored_EC3.md";

/// The ledger.
pub const LEDGER: &str = "doc/conformance/ledger.toml";

/// The directories whose Rust sources are scanned for citations.
///
/// Everything this project writes, including its build scripts and fuzz targets: a wrong
/// clause number is wrong wherever it is written.
pub const SOURCE_ROOTS: [&str; 3] = ["crates", "tools", "fuzz"];

/// The workspace root, from this crate's own location.
#[must_use]
pub fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Scans every Rust source under [`SOURCE_ROOTS`], with paths relative to `root`.
///
/// # Errors
///
/// If a directory cannot be read: a checker that skipped what it could not open would
/// report a clean tree for a tree it had not looked at.
pub fn scan_tree(root: &Path) -> std::io::Result<Vec<(PathBuf, Scan)>> {
    let roots: Vec<PathBuf> = SOURCE_ROOTS.iter().map(|name| root.join(name)).collect();
    let mut scanned = Vec::new();
    for path in citation::rust_sources(&roots)? {
        let relative = path.strip_prefix(root).unwrap_or(&path).to_path_buf();
        if relative.starts_with(NOT_SCANNED) {
            continue;
        }
        let source = std::fs::read_to_string(&path)?;
        scanned.push((relative, citation::scan(&source)));
    }
    Ok(scanned)
}

/// The one directory the scan does not read: the checker's own.
///
/// Stated rather than quietly skipped, because a checker that does not look somewhere should
/// say where. Two reasons, and neither generalises to any other crate:
///
/// - **Its comments name clauses that do not exist, deliberately.** `§8.9.6.5` and
///   `§11.4.5.6` are the two wrong numbers that motivated this crate, and three of its files
///   quote them while explaining what went wrong. Scanning it would report its own
///   documentation as findings, which is the fastest way to have a gate switched off.
/// - **Its citations are examples rather than claims.** Everything else that names a clause
///   is code implementing it or a test holding it, and the ledger asks such a citation to be
///   backed by a reviewed row. This crate names clauses to explain *clause numbering* — that
///   `§8.9.6`'s text lives in `§8.9.6.2`, that `§14.8` is renumbered by the corrigendum — and
///   reviewing tagged PDF because a comment here mentions it would enforce the wrong thing.
///
/// The cost is that the checker's own citations are checked by reading, like everything else
/// was before it existed.
pub const NOT_SCANNED: &str = "tools/conformance";

/// Every citation the tree makes, paired with the file that makes it.
#[must_use]
pub fn citations(scanned: &[(PathBuf, Scan)]) -> Vec<(PathBuf, Citation)> {
    scanned
        .iter()
        .flat_map(|(path, scan)| {
            scan.citations
                .iter()
                .map(move |citation| (path.clone(), citation.clone()))
        })
        .collect()
}
